//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_DatVeMayBay.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietChuyenBay
    {
        public int MaCTCB { get; set; }
        public string MaChuyenBay { get; set; }
        public string MaSanBayTG { get; set; }
        public int ThoiGianDung { get; set; }
        public int ThuTuDung { get; set; }
        public string GhiChu { get; set; }
    
        public virtual ChuyenBay ChuyenBay { get; set; }
        public virtual SanBay SanBay { get; set; }
    }
}
