//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_DatVeMayBay.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChuyenBay
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChuyenBay()
        {
            this.ChiTietChuyenBay = new HashSet<ChiTietChuyenBay>();
            this.DanhGiaChuyenBay = new HashSet<DanhGiaChuyenBay>();
            this.VeMayBay = new HashSet<VeMayBay>();
            this.YeuCauHuyDoiVe = new HashSet<YeuCauHuyDoiVe>();
        }
    
        public string MaChuyenBay { get; set; }
        public string MaTuyenBay { get; set; }
        public string MaMayBay { get; set; }
        public System.DateTime NgayGioBay { get; set; }
        public System.DateTime NgayGioDenDK { get; set; }
        public Nullable<int> ThoiGianBay { get; set; }
        public decimal GiaVeCoBan { get; set; }
        public int SoGheTrong { get; set; }
        public string TrangThai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietChuyenBay> ChiTietChuyenBay { get; set; }
        public virtual MayBay MayBay { get; set; }
        public virtual TuyenBay TuyenBay { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DanhGiaChuyenBay> DanhGiaChuyenBay { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VeMayBay> VeMayBay { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YeuCauHuyDoiVe> YeuCauHuyDoiVe { get; set; }
    }
}
