//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_DatVeMayBay.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhGiaChuyenBay
    {
        public int MaDanhGia { get; set; }
        public string MaKH { get; set; }
        public string MaChuyenBay { get; set; }
        public int SoSao { get; set; }
        public string NoiDung { get; set; }
        public Nullable<System.DateTime> NgayDanhGia { get; set; }
    
        public virtual ChuyenBay ChuyenBay { get; set; }
        public virtual KhachHang KhachHang { get; set; }
    }
}
