//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_DatVeMayBay.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class GheNgoi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GheNgoi()
        {
            this.VeMayBay = new HashSet<VeMayBay>();
            this.YeuCauHuyDoiVe = new HashSet<YeuCauHuyDoiVe>();
        }
    
        public int MaGhe { get; set; }
        public string MaMayBay { get; set; }
        public string SoGhe { get; set; }
        public string MaHangGhe { get; set; }
        public Nullable<bool> TrangThai { get; set; }
    
        public virtual HangGhe HangGhe { get; set; }
        public virtual MayBay MayBay { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VeMayBay> VeMayBay { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YeuCauHuyDoiVe> YeuCauHuyDoiVe { get; set; }
    }
}
