//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_DatVeMayBay.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        public string MaHD { get; set; }
        public string MaDatCho { get; set; }
        public string MaNV { get; set; }
        public Nullable<System.DateTime> NgayLap { get; set; }
        public decimal TongTien { get; set; }
        public string PhuongThuc { get; set; }
        public string MaGiaoDichNganHang { get; set; }
        public Nullable<System.DateTime> NgayThanhToan { get; set; }
        public string TrangThai { get; set; }
        public string GhiChu { get; set; }
    
        public virtual PhieuDatCho PhieuDatCho { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
