//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_DatVeMayBay.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QL_DatVeMayBayEntities : DbContext
    {
        public QL_DatVeMayBayEntities()
            : base("name=QL_DatVeMayBayEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChiTietChuyenBay> ChiTietChuyenBay { get; set; }
        public virtual DbSet<ChuyenBay> ChuyenBay { get; set; }
        public virtual DbSet<DanhGiaChuyenBay> DanhGiaChuyenBay { get; set; }
        public virtual DbSet<GheNgoi> GheNgoi { get; set; }
        public virtual DbSet<HangGhe> HangGhe { get; set; }
        public virtual DbSet<HangHangKhong> HangHangKhong { get; set; }
        public virtual DbSet<HoaDon> HoaDon { get; set; }
        public virtual DbSet<KhachHang> KhachHang { get; set; }
        public virtual DbSet<KhuyenMai> KhuyenMai { get; set; }
        public virtual DbSet<MayBay> MayBay { get; set; }
        public virtual DbSet<NhanVien> NhanVien { get; set; }
        public virtual DbSet<PhieuDatCho> PhieuDatCho { get; set; }
        public virtual DbSet<SanBay> SanBay { get; set; }
        public virtual DbSet<TuyenBay> TuyenBay { get; set; }
        public virtual DbSet<VaiTro> VaiTro { get; set; }
        public virtual DbSet<VeMayBay> VeMayBay { get; set; }
        public virtual DbSet<YeuCauHuyDoiVe> YeuCauHuyDoiVe { get; set; }
        public virtual DbSet<vw_BaoCaoDoanhThuTheoHang> vw_BaoCaoDoanhThuTheoHang { get; set; }
        public virtual DbSet<vw_ChiTietVeVaHanhKhach> vw_ChiTietVeVaHanhKhach { get; set; }
        public virtual DbSet<vw_DanhSachChuyenBayChiTiet> vw_DanhSachChuyenBayChiTiet { get; set; }
        public virtual DbSet<vw_LichSuDatVeKhachHang> vw_LichSuDatVeKhachHang { get; set; }
        public virtual DbSet<vw_TopTuyenBayDatNhieuNhat> vw_TopTuyenBayDatNhieuNhat { get; set; }
    
        [DbFunction("QL_DatVeMayBayEntities", "fn_TinhTienHoanTraHuyVe")]
        public virtual IQueryable<fn_TinhTienHoanTraHuyVe_Result> fn_TinhTienHoanTraHuyVe(string maVe)
        {
            var maVeParameter = maVe != null ?
                new ObjectParameter("MaVe", maVe) :
                new ObjectParameter("MaVe", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_TinhTienHoanTraHuyVe_Result>("[QL_DatVeMayBayEntities].[fn_TinhTienHoanTraHuyVe](@MaVe)", maVeParameter);
        }
    
        public virtual ObjectResult<sp_DangKyKhachHang_Result> sp_DangKyKhachHang(string tenKH, string gioiTinh, Nullable<System.DateTime> ngaySinh, string sDT, string email, string matKhau, string diaChi, string loaiKhachHang, string cCCD, string hoChieu, string quocTich, string coQuanCongTac, string soTK_DoanhNghiep)
        {
            var tenKHParameter = tenKH != null ?
                new ObjectParameter("TenKH", tenKH) :
                new ObjectParameter("TenKH", typeof(string));
    
            var gioiTinhParameter = gioiTinh != null ?
                new ObjectParameter("GioiTinh", gioiTinh) :
                new ObjectParameter("GioiTinh", typeof(string));
    
            var ngaySinhParameter = ngaySinh.HasValue ?
                new ObjectParameter("NgaySinh", ngaySinh) :
                new ObjectParameter("NgaySinh", typeof(System.DateTime));
    
            var sDTParameter = sDT != null ?
                new ObjectParameter("SDT", sDT) :
                new ObjectParameter("SDT", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var matKhauParameter = matKhau != null ?
                new ObjectParameter("MatKhau", matKhau) :
                new ObjectParameter("MatKhau", typeof(string));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("DiaChi", diaChi) :
                new ObjectParameter("DiaChi", typeof(string));
    
            var loaiKhachHangParameter = loaiKhachHang != null ?
                new ObjectParameter("LoaiKhachHang", loaiKhachHang) :
                new ObjectParameter("LoaiKhachHang", typeof(string));
    
            var cCCDParameter = cCCD != null ?
                new ObjectParameter("CCCD", cCCD) :
                new ObjectParameter("CCCD", typeof(string));
    
            var hoChieuParameter = hoChieu != null ?
                new ObjectParameter("HoChieu", hoChieu) :
                new ObjectParameter("HoChieu", typeof(string));
    
            var quocTichParameter = quocTich != null ?
                new ObjectParameter("QuocTich", quocTich) :
                new ObjectParameter("QuocTich", typeof(string));
    
            var coQuanCongTacParameter = coQuanCongTac != null ?
                new ObjectParameter("CoQuanCongTac", coQuanCongTac) :
                new ObjectParameter("CoQuanCongTac", typeof(string));
    
            var soTK_DoanhNghiepParameter = soTK_DoanhNghiep != null ?
                new ObjectParameter("SoTK_DoanhNghiep", soTK_DoanhNghiep) :
                new ObjectParameter("SoTK_DoanhNghiep", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_DangKyKhachHang_Result>("sp_DangKyKhachHang", tenKHParameter, gioiTinhParameter, ngaySinhParameter, sDTParameter, emailParameter, matKhauParameter, diaChiParameter, loaiKhachHangParameter, cCCDParameter, hoChieuParameter, quocTichParameter, coQuanCongTacParameter, soTK_DoanhNghiepParameter);
        }
    
        public virtual ObjectResult<sp_DangNhapKhachHang_Result> sp_DangNhapKhachHang(string taiKhoan)
        {
            var taiKhoanParameter = taiKhoan != null ?
                new ObjectParameter("TaiKhoan", taiKhoan) :
                new ObjectParameter("TaiKhoan", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_DangNhapKhachHang_Result>("sp_DangNhapKhachHang", taiKhoanParameter);
        }
    
        public virtual int sp_DatVeMayBay_Batch(string maDatCho, string maKH, string maChuyenBay, string maKM, string ghiChu)
        {
            var maDatChoParameter = maDatCho != null ?
                new ObjectParameter("MaDatCho", maDatCho) :
                new ObjectParameter("MaDatCho", typeof(string));
    
            var maKHParameter = maKH != null ?
                new ObjectParameter("MaKH", maKH) :
                new ObjectParameter("MaKH", typeof(string));
    
            var maChuyenBayParameter = maChuyenBay != null ?
                new ObjectParameter("MaChuyenBay", maChuyenBay) :
                new ObjectParameter("MaChuyenBay", typeof(string));
    
            var maKMParameter = maKM != null ?
                new ObjectParameter("MaKM", maKM) :
                new ObjectParameter("MaKM", typeof(string));
    
            var ghiChuParameter = ghiChu != null ?
                new ObjectParameter("GhiChu", ghiChu) :
                new ObjectParameter("GhiChu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DatVeMayBay_Batch", maDatChoParameter, maKHParameter, maChuyenBayParameter, maKMParameter, ghiChuParameter);
        }
    
        public virtual ObjectResult<sp_DoiVeMayBay_Result> sp_DoiVeMayBay(string maVeCu, string maChuyenBayMoi, Nullable<int> maGheMoi, string maHangGheMoi, string maNVXuLy)
        {
            var maVeCuParameter = maVeCu != null ?
                new ObjectParameter("MaVeCu", maVeCu) :
                new ObjectParameter("MaVeCu", typeof(string));
    
            var maChuyenBayMoiParameter = maChuyenBayMoi != null ?
                new ObjectParameter("MaChuyenBayMoi", maChuyenBayMoi) :
                new ObjectParameter("MaChuyenBayMoi", typeof(string));
    
            var maGheMoiParameter = maGheMoi.HasValue ?
                new ObjectParameter("MaGheMoi", maGheMoi) :
                new ObjectParameter("MaGheMoi", typeof(int));
    
            var maHangGheMoiParameter = maHangGheMoi != null ?
                new ObjectParameter("MaHangGheMoi", maHangGheMoi) :
                new ObjectParameter("MaHangGheMoi", typeof(string));
    
            var maNVXuLyParameter = maNVXuLy != null ?
                new ObjectParameter("MaNVXuLy", maNVXuLy) :
                new ObjectParameter("MaNVXuLy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_DoiVeMayBay_Result>("sp_DoiVeMayBay", maVeCuParameter, maChuyenBayMoiParameter, maGheMoiParameter, maHangGheMoiParameter, maNVXuLyParameter);
        }
    
        public virtual ObjectResult<sp_TimKiemChuyenBay_Result> sp_TimKiemChuyenBay(string maSanBayDi, string maSanBayDen, Nullable<System.DateTime> ngayBay, string maHangGhe, Nullable<decimal> giaMax, string maHang)
        {
            var maSanBayDiParameter = maSanBayDi != null ?
                new ObjectParameter("MaSanBayDi", maSanBayDi) :
                new ObjectParameter("MaSanBayDi", typeof(string));
    
            var maSanBayDenParameter = maSanBayDen != null ?
                new ObjectParameter("MaSanBayDen", maSanBayDen) :
                new ObjectParameter("MaSanBayDen", typeof(string));
    
            var ngayBayParameter = ngayBay.HasValue ?
                new ObjectParameter("NgayBay", ngayBay) :
                new ObjectParameter("NgayBay", typeof(System.DateTime));
    
            var maHangGheParameter = maHangGhe != null ?
                new ObjectParameter("MaHangGhe", maHangGhe) :
                new ObjectParameter("MaHangGhe", typeof(string));
    
            var giaMaxParameter = giaMax.HasValue ?
                new ObjectParameter("GiaMax", giaMax) :
                new ObjectParameter("GiaMax", typeof(decimal));
    
            var maHangParameter = maHang != null ?
                new ObjectParameter("MaHang", maHang) :
                new ObjectParameter("MaHang", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_TimKiemChuyenBay_Result>("sp_TimKiemChuyenBay", maSanBayDiParameter, maSanBayDenParameter, ngayBayParameter, maHangGheParameter, giaMaxParameter, maHangParameter);
        }
    
        public virtual int sp_TuDongHuyDonGiuChoHetHan_Cursor()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_TuDongHuyDonGiuChoHetHan_Cursor");
        }
    
        public virtual ObjectResult<sp_ThanhToanDonVe_Result> sp_ThanhToanDonVe(string maHD, string maDatCho, string maNV, string phuongThuc, string maGiaoDich)
        {
            var maHDParameter = maHD != null ?
                new ObjectParameter("MaHD", maHD) :
                new ObjectParameter("MaHD", typeof(string));
    
            var maDatChoParameter = maDatCho != null ?
                new ObjectParameter("MaDatCho", maDatCho) :
                new ObjectParameter("MaDatCho", typeof(string));
    
            var maNVParameter = maNV != null ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(string));
    
            var phuongThucParameter = phuongThuc != null ?
                new ObjectParameter("PhuongThuc", phuongThuc) :
                new ObjectParameter("PhuongThuc", typeof(string));
    
            var maGiaoDichParameter = maGiaoDich != null ?
                new ObjectParameter("MaGiaoDich", maGiaoDich) :
                new ObjectParameter("MaGiaoDich", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ThanhToanDonVe_Result>("sp_ThanhToanDonVe", maHDParameter, maDatChoParameter, maNVParameter, phuongThucParameter, maGiaoDichParameter);
        }
    
        public virtual ObjectResult<sp_XuLyHuyVeVaHoanTien_Result> sp_XuLyHuyVeVaHoanTien(string maVe, string lyDo, string maNVXuLy)
        {
            var maVeParameter = maVe != null ?
                new ObjectParameter("MaVe", maVe) :
                new ObjectParameter("MaVe", typeof(string));
    
            var lyDoParameter = lyDo != null ?
                new ObjectParameter("LyDo", lyDo) :
                new ObjectParameter("LyDo", typeof(string));
    
            var maNVXuLyParameter = maNVXuLy != null ?
                new ObjectParameter("MaNVXuLy", maNVXuLy) :
                new ObjectParameter("MaNVXuLy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_XuLyHuyVeVaHoanTien_Result>("sp_XuLyHuyVeVaHoanTien", maVeParameter, lyDoParameter, maNVXuLyParameter);
        }
    }
}
