//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_DatVeMayBay.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VeMayBay
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VeMayBay()
        {
            this.YeuCauHuyDoiVe = new HashSet<YeuCauHuyDoiVe>();
        }
    
        public string MaVe { get; set; }
        public string MaDatCho { get; set; }
        public string MaChuyenBay { get; set; }
        public int MaGhe { get; set; }
        public string MaHangGhe { get; set; }
        public string TenHanhKhach { get; set; }
        public string CCCD_HanhKhach { get; set; }
        public string LoaiHanhKhach { get; set; }
        public decimal GiaVe { get; set; }
        public string TrangThai { get; set; }
    
        public virtual ChuyenBay ChuyenBay { get; set; }
        public virtual GheNgoi GheNgoi { get; set; }
        public virtual HangGhe HangGhe { get; set; }
        public virtual PhieuDatCho PhieuDatCho { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YeuCauHuyDoiVe> YeuCauHuyDoiVe { get; set; }
    }
}
