//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_DatVeMayBay.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_BaoCaoDoanhThuTheoHang
    {
        public string MaHang { get; set; }
        public string TenHang { get; set; }
        public Nullable<int> TongSoVeDaBan { get; set; }
        public Nullable<decimal> TongDoanhThuVe { get; set; }
    }
}
