//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_DatVeMayBay.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ChiTietVeVaHanhKhach
    {
        public string MaVe { get; set; }
        public string MaDatCho { get; set; }
        public string TenHanhKhach { get; set; }
        public string CCCD_HanhKhach { get; set; }
        public string LoaiHanhKhach { get; set; }
        public decimal GiaVe { get; set; }
        public string TrangThaiVe { get; set; }
        public string TenHangGhe { get; set; }
        public string SoGhe { get; set; }
        public string MaChuyenBay { get; set; }
        public string HangBay { get; set; }
        public string SanBayDi { get; set; }
        public string ThanhPhoDi { get; set; }
        public string SanBayDen { get; set; }
        public string ThanhPhoDen { get; set; }
        public System.DateTime NgayGioBay { get; set; }
        public System.DateTime NgayGioDenDK { get; set; }
    }
}
