//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_DatVeMayBay.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_DanhSachChuyenBayChiTiet
    {
        public string MaChuyenBay { get; set; }
        public string MaHang { get; set; }
        public string TenHangHangKhong { get; set; }
        public string Logo { get; set; }
        public string MaMayBay { get; set; }
        public string TenMayBay { get; set; }
        public string MaTuyenBay { get; set; }
        public string MaSanBayDi { get; set; }
        public string TenSanBayDi { get; set; }
        public string ThanhPhoDi { get; set; }
        public string MaSanBayDen { get; set; }
        public string TenSanBayDen { get; set; }
        public string ThanhPhoDen { get; set; }
        public System.DateTime NgayGioBay { get; set; }
        public System.DateTime NgayGioDenDK { get; set; }
        public Nullable<int> ThoiGianBay { get; set; }
        public decimal GiaVeCoBan { get; set; }
        public int SoGheTrong { get; set; }
        public int TongSoGhe { get; set; }
        public string TrangThaiChuyenBay { get; set; }
    }
}
