//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_DatVeMayBay.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class YeuCauHuyDoiVe
    {
        public int MaYeuCau { get; set; }
        public string MaVe { get; set; }
        public string LoaiYeuCau { get; set; }
        public Nullable<System.DateTime> NgayYeuCau { get; set; }
        public string LyDo { get; set; }
        public string MaChuyenBayMoi { get; set; }
        public Nullable<int> MaGheMoi { get; set; }
        public Nullable<decimal> PhanTramHoan { get; set; }
        public Nullable<decimal> SoTienGoc { get; set; }
        public Nullable<decimal> PhiPhat { get; set; }
        public Nullable<decimal> SoTienHoan { get; set; }
        public Nullable<decimal> PhiChenhLech { get; set; }
        public string TrangThai { get; set; }
        public string MaNVXuLy { get; set; }
        public Nullable<System.DateTime> NgayXuLy { get; set; }
        public string GhiChu { get; set; }
    
        public virtual ChuyenBay ChuyenBay { get; set; }
        public virtual GheNgoi GheNgoi { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        public virtual VeMayBay VeMayBay { get; set; }
    }
}
